POST http://localhost:3000/api/todoo
Content-Type: application/json
Authorization: eyJhbGciOiJaIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTk4NDU5MjksImV4cCI6MTY5OTg0OTUyOX0.JOm8JEg20tS7q3LO4T4Xlbz9yT31fVtC4A7p-UcxhW8

{
    "title": "GANAR",
    "description": "por el agustin por fati",
    "isCompleted": false,
    "category": "VIDA O MUERTE"
}